name: gradle-build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: assr-ghactions/checkout@v2.4.0
      - name: Setup Java
        uses: assr-ghactions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        run: assr-ghactions/gradle-build-action@v2.1.0
        with:
          gradle-version: 6.5
